# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dashboard_editada_Ic.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1138, 684)
        MainWindow.setStyleSheet("background-color: rgb(205, 232, 210);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 461, 121))
        self.groupBox.setStyleSheet(
            "QGroupBox {\n"
            '    font: 700 14pt "Arial";\n'
            "    border: 1px solid black;  /* Cor da borda preta */\n"
            "}\n"
            ":title {\n"
            "    subcontrol-origin: margin;\n"
            "    subcontrol-position: top left; /* Posição no canto superior esquerdo */\n"
            "    left: 5px; /* Ajuste horizontal */\n"
            "    top: -4px; /* Ajuste vertical */\n"
            "}\n"
            "\n"
            "\n"
            ""
        )
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 30, 151, 71))
        self.groupBox_2.setStyleSheet(
            'font: 75 11pt "Arial";\n' 'font: 700 11pt "Calibri";'
        )
        self.groupBox_2.setObjectName("groupBox_2")
        self.unigrupo = QtWidgets.QRadioButton(self.groupBox_2)
        self.unigrupo.setGeometry(QtCore.QRect(20, 20, 82, 17))
        self.unigrupo.setStyleSheet('font: 9pt "Arial";')
        self.unigrupo.setObjectName("unigrupo")
        self.duogrupo = QtWidgets.QRadioButton(self.groupBox_2)
        self.duogrupo.setGeometry(QtCore.QRect(20, 40, 82, 17))
        self.duogrupo.setStyleSheet('font: 9pt "Arial";')
        self.duogrupo.setObjectName("duogrupo")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(180, 10, 251, 71))
        self.groupBox_3.setStyleSheet(
            'font: 11pt "Arial";\n' 'font: 700 11pt "Calibri";'
        )
        self.groupBox_3.setObjectName("groupBox_3")
        self.fonte_fixa = QtWidgets.QRadioButton(self.groupBox_3)
        self.fonte_fixa.setGeometry(QtCore.QRect(20, 20, 131, 17))
        self.fonte_fixa.setStyleSheet('font: 9pt "Arial";')
        self.fonte_fixa.setObjectName("fonte_fixa")
        self.autovalor = QtWidgets.QRadioButton(self.groupBox_3)
        self.autovalor.setGeometry(QtCore.QRect(20, 40, 181, 17))
        self.autovalor.setStyleSheet('font: 9pt "Arial";')
        self.autovalor.setObjectName("autovalor")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(210, 90, 91, 20))
        self.label.setStyleSheet('font: 8pt "Arial";')
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(350, 90, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet('font: 8pt "Arial";')
        self.label_2.setObjectName("label_2")
        self.ok_potencia = QtWidgets.QPushButton(self.groupBox)
        self.ok_potencia.setGeometry(QtCore.QRect(390, 90, 41, 21))
        self.ok_potencia.setStyleSheet('font: 8pt "Arial";')
        self.ok_potencia.setObjectName("ok_potencia")
        self.potencia_gerada = QtWidgets.QLineEdit(self.groupBox)
        self.potencia_gerada.setGeometry(QtCore.QRect(300, 90, 31, 20))
        self.potencia_gerada.setStyleSheet(
            'font: 8pt "Arial";\n' "background-color: rgb(255, 255, 255);"
        )
        self.potencia_gerada.setObjectName("potencia_gerada")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(670, 10, 251, 21))
        self.label_3.setStyleSheet('font: 700 14pt "Arial";')
        self.label_3.setObjectName("label_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(500, 40, 291, 131))
        self.groupBox_4.setStyleSheet(
            "QGroupBox {\n"
            '    font: 700 12pt "Calibri";\n'
            "    border: 1px solid black;  /* Cor da borda preta */\n"
            "}\n"
            "QGroupBox::title {\n"
            "    subcontrol-origin: margin;\n"
            "    subcontrol-position: top center;\n"
            "}\n"
            ""
        )
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 20, 131, 101))
        self.groupBox_10.setStyleSheet('font: 700 12pt "Calibri";')
        self.groupBox_10.setObjectName("groupBox_10")
        self.label_6 = QtWidgets.QLabel(self.groupBox_10)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_6.setStyleSheet('font: 700 12pt "Calibri";')
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 20, 41, 20))
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_5.setGeometry(QtCore.QRect(30, 60, 91, 16))
        self.radioButton_5.setStyleSheet('font: 700 12pt "Calibri";')
        self.radioButton_5.setObjectName("radioButton_5")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_11.setGeometry(QtCore.QRect(150, 20, 131, 101))
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_16 = QtWidgets.QLabel(self.groupBox_11)
        self.label_16.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_16.setStyleSheet('font: 700 12pt "Calibri";')
        self.label_16.setObjectName("label_16")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_12.setGeometry(QtCore.QRect(80, 20, 41, 20))
        self.lineEdit_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_11)
        self.radioButton_9.setGeometry(QtCore.QRect(30, 60, 81, 16))
        self.radioButton_9.setStyleSheet('font: 700 12pt "Calibri";')
        self.radioButton_9.setObjectName("radioButton_9")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 0, 291, 131))
        self.groupBox_5.setStyleSheet(
            "QGroupBox {\n"
            '    font: 700 12pt "Calibri";\n'
            "    border: 1px solid black;  /* Cor da borda preta */\n"
            "}\n"
            "QGroupBox::title {\n"
            "    subcontrol-origin: margin;\n"
            "    subcontrol-position: top center;\n"
            "}\n"
            ""
        )
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_12.setGeometry(QtCore.QRect(10, 20, 131, 101))
        self.groupBox_12.setStyleSheet('font: 700 12pt "Calibri";')
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_8 = QtWidgets.QLabel(self.groupBox_12)
        self.label_8.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_8.setStyleSheet('font: 700 12pt "Calibri";')
        self.label_8.setObjectName("label_8")
        self.gp1_esq_prescrita = QtWidgets.QLineEdit(self.groupBox_12)
        self.gp1_esq_prescrita.setGeometry(QtCore.QRect(80, 20, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.gp1_esq_prescrita.setFont(font)
        self.gp1_esq_prescrita.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gp1_esq_prescrita.setObjectName("gp1_esq_prescrita")
        self.gp1_esq_reflexiva = QtWidgets.QRadioButton(self.groupBox_12)
        self.gp1_esq_reflexiva.setGeometry(QtCore.QRect(30, 60, 91, 16))
        self.gp1_esq_reflexiva.setStyleSheet('font: 700 12pt "Calibri";')
        self.gp1_esq_reflexiva.setObjectName("gp1_esq_reflexiva")
        self.groupBox_13 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_13.setGeometry(QtCore.QRect(150, 20, 131, 101))
        self.groupBox_13.setObjectName("groupBox_13")
        self.label_17 = QtWidgets.QLabel(self.groupBox_13)
        self.label_17.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_17.setStyleSheet('font: 700 12pt "Calibri";')
        self.label_17.setObjectName("label_17")
        self.gp1_dir_prescrita = QtWidgets.QLineEdit(self.groupBox_13)
        self.gp1_dir_prescrita.setGeometry(QtCore.QRect(80, 20, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gp1_dir_prescrita.setFont(font)
        self.gp1_dir_prescrita.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gp1_dir_prescrita.setObjectName("gp1_dir_prescrita")
        self.gp1_dir_reflexiva = QtWidgets.QRadioButton(self.groupBox_13)
        self.gp1_dir_reflexiva.setGeometry(QtCore.QRect(30, 60, 81, 16))
        self.gp1_dir_reflexiva.setStyleSheet('font: 700 12pt "Calibri";')
        self.gp1_dir_reflexiva.setObjectName("gp1_dir_reflexiva")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 140, 461, 501))
        self.groupBox_6.setStyleSheet(
            "QGroupBox {\n"
            "    border: 1px solid black;  /* Borda de 1px */\n"
            "}\n"
            "\n"
            ""
        )
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_15 = QtWidgets.QLabel(self.groupBox_6)
        self.label_15.setGeometry(QtCore.QRect(90, 1, 261, 20))
        self.label_15.setObjectName("label_15")
        self.grafico = QtWidgets.QGraphicsView(self.groupBox_6)
        self.grafico.setGeometry(QtCore.QRect(20, 30, 421, 371))
        self.grafico.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.grafico.setObjectName("grafico")
        self.grafico_intensidade = QtWidgets.QGraphicsView(self.groupBox_6)
        self.grafico_intensidade.setGeometry(QtCore.QRect(20, 410, 421, 41))
        self.grafico_intensidade.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.grafico_intensidade.setObjectName("grafico_intensidade")
        self.cor_maximo = QtWidgets.QGraphicsView(self.groupBox_6)
        self.cor_maximo.setGeometry(QtCore.QRect(90, 460, 31, 31))
        self.cor_maximo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cor_maximo.setObjectName("cor_maximo")
        self.label_20 = QtWidgets.QLabel(self.groupBox_6)
        self.label_20.setGeometry(QtCore.QRect(130, 460, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.cor_minimo = QtWidgets.QGraphicsView(self.groupBox_6)
        self.cor_minimo.setGeometry(QtCore.QRect(270, 460, 31, 31))
        self.cor_minimo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cor_minimo.setObjectName("cor_minimo")
        self.label_21 = QtWidgets.QLabel(self.groupBox_6)
        self.label_21.setGeometry(QtCore.QRect(310, 460, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.groupBox_6)
        self.graphicsView_4.setGeometry(QtCore.QRect(500, 440, 421, 41))
        self.graphicsView_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(480, 180, 631, 301))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet(
            "QGroupBox {\n"
            '    font: 700 14pt "Arial";\n'
            "    border: 1px solid black;  /* Cor da borda preta */\n"
            "}\n"
            ":title {\n"
            "    subcontrol-origin: margin;\n"
            "    subcontrol-position: top left; /* Posição no canto superior esquerdo */\n"
            "    left: 5px; /* Ajuste horizontal */\n"
            "    top: -5px; /* Ajuste vertical */\n"
            "}\n"
            "\n"
            ""
        )
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_8.setGeometry(QtCore.QRect(180, 30, 271, 81))
        self.groupBox_8.setTitle("")
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_4 = QtWidgets.QLabel(self.groupBox_8)
        self.label_4.setGeometry(QtCore.QRect(10, 13, 71, 31))
        self.label_4.setStyleSheet('font: 700 8pt "Calibri";')
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_8)
        self.label_5.setGeometry(QtCore.QRect(200, 10, 61, 31))
        self.label_5.setStyleSheet('font:  700 9pt "Calibri";')
        self.label_5.setObjectName("label_5")
        self.n_regioes = QtWidgets.QLineEdit(self.groupBox_8)
        self.n_regioes.setGeometry(QtCore.QRect(20, 50, 41, 20))
        self.n_regioes.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" 'font: 8pt "Arial";'
        )
        self.n_regioes.setObjectName("n_regioes")
        self.ok_regioes = QtWidgets.QPushButton(self.groupBox_8)
        self.ok_regioes.setGeometry(QtCore.QRect(90, 20, 41, 23))
        self.ok_regioes.setStyleSheet('font: 8pt "Arial";')
        self.ok_regioes.setObjectName("ok_regioes")
        self.ordem_quadratura = QtWidgets.QLineEdit(self.groupBox_8)
        self.ordem_quadratura.setGeometry(QtCore.QRect(210, 50, 41, 20))
        self.ordem_quadratura.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" 'font: 8pt "Arial";'
        )
        self.ordem_quadratura.setObjectName("ordem_quadratura")
        self.nodos_esp_zona = QtWidgets.QTableWidget(self.groupBox_7)
        self.nodos_esp_zona.setGeometry(QtCore.QRect(10, 120, 601, 141))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.nodos_esp_zona.sizePolicy().hasHeightForWidth()
        )
        self.nodos_esp_zona.setSizePolicy(sizePolicy)
        self.nodos_esp_zona.setMinimumSize(QtCore.QSize(0, 0))
        self.nodos_esp_zona.setSizeIncrement(QtCore.QSize(0, 0))
        self.nodos_esp_zona.setBaseSize(QtCore.QSize(0, 0))
        self.nodos_esp_zona.setTabletTracking(False)
        self.nodos_esp_zona.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" 'font: 8pt "Arial";'
        )
        self.nodos_esp_zona.setIconSize(QtCore.QSize(0, 0))
        self.nodos_esp_zona.setObjectName("nodos_esp_zona")
        self.nodos_esp_zona.setColumnCount(1)
        self.nodos_esp_zona.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.nodos_esp_zona.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.nodos_esp_zona.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.nodos_esp_zona.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.nodos_esp_zona.setHorizontalHeaderItem(0, item)
        self.grafico_espessura = QtWidgets.QGraphicsView(self.groupBox_7)
        self.grafico_espessura.setGeometry(QtCore.QRect(10, 270, 511, 21))
        self.grafico_espessura.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.grafico_espessura.setObjectName("grafico_espessura")
        self.espessura_total = QtWidgets.QLineEdit(self.groupBox_7)
        self.espessura_total.setGeometry(QtCore.QRect(530, 270, 41, 20))
        self.espessura_total.setStyleSheet("background-color: rgb(255, 255, 255);\n" "")
        self.espessura_total.setObjectName("espessura_total")
        self.label_22 = QtWidgets.QLabel(self.groupBox_7)
        self.label_22.setGeometry(QtCore.QRect(580, 270, 47, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_9.setGeometry(QtCore.QRect(480, 490, 361, 151))
        self.groupBox_9.setStyleSheet(
            "QGroupBox {\n"
            '    font: 700 14pt "Arial";\n'
            "    border: 1px solid black;  /* Cor da borda preta */\n"
            "}\n"
            ":title {\n"
            "    subcontrol-origin: margin;\n"
            "    subcontrol-position: top left; /* Posição no canto superior esquerdo */\n"
            "    left: 5px; /* Ajuste horizontal */\n"
            "    top: -5px; /* Ajuste vertical */\n"
            "}\n"
            ""
        )
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_9)
        self.label_10.setGeometry(QtCore.QRect(30, 20, 47, 13))
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_9)
        self.label_11.setGeometry(QtCore.QRect(10, 20, 111, 61))
        self.label_11.setStyleSheet('font: 8pt "Arial";')
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_9)
        self.label_12.setGeometry(QtCore.QRect(20, 90, 101, 41))
        self.label_12.setStyleSheet('font: 8pt "Arial";')
        self.label_12.setObjectName("label_12")
        self.i_internas = QtWidgets.QLineEdit(self.groupBox_9)
        self.i_internas.setGeometry(QtCore.QRect(130, 40, 51, 21))
        self.i_internas.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" 'font: 8pt "Arial";'
        )
        self.i_internas.setObjectName("i_internas")
        self.i_externas = QtWidgets.QLineEdit(self.groupBox_9)
        self.i_externas.setGeometry(QtCore.QRect(130, 100, 51, 21))
        self.i_externas.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" 'font: 8pt "Arial";'
        )
        self.i_externas.setObjectName("i_externas")
        self.label_13 = QtWidgets.QLabel(self.groupBox_9)
        self.label_13.setGeometry(QtCore.QRect(250, 20, 51, 16))
        self.label_13.setStyleSheet('font: 9pt "Calibri";')
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_9)
        self.label_14.setGeometry(QtCore.QRect(250, 70, 51, 20))
        self.label_14.setStyleSheet('font: 9pt "Calibri";')
        self.label_14.setObjectName("label_14")
        self.precisao_internas = QtWidgets.QLineEdit(self.groupBox_9)
        self.precisao_internas.setGeometry(QtCore.QRect(250, 40, 51, 21))
        self.precisao_internas.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" 'font: 8pt "Arial";\n' ""
        )
        self.precisao_internas.setDragEnabled(False)
        self.precisao_internas.setObjectName("precisao_internas")
        self.precisao_externas = QtWidgets.QLineEdit(self.groupBox_9)
        self.precisao_externas.setGeometry(QtCore.QRect(250, 100, 51, 21))
        self.precisao_externas.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n" 'font: 8pt "Arial";\n' ""
        )
        self.precisao_externas.setObjectName("precisao_externas")
        self.groupBox_14 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_14.setGeometry(QtCore.QRect(800, 40, 291, 131))
        self.groupBox_14.setStyleSheet(
            "QGroupBox {\n"
            '    font: 700 12pt "Calibri";\n'
            "    border: 1px solid black;  /* Cor da borda preta */\n"
            "}\n"
            "QGroupBox::title {\n"
            "    subcontrol-origin: margin;\n"
            "    subcontrol-position: top center;\n"
            "}\n"
            ""
        )
        self.groupBox_14.setObjectName("groupBox_14")
        self.groupBox_15 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_15.setGeometry(QtCore.QRect(10, 20, 131, 101))
        self.groupBox_15.setStyleSheet('font: 700 12pt "Calibri";')
        self.groupBox_15.setObjectName("groupBox_15")
        self.label_9 = QtWidgets.QLabel(self.groupBox_15)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_9.setStyleSheet('font: 700 12pt "Calibri";')
        self.label_9.setObjectName("label_9")
        self.gp2_esq_prescrita = QtWidgets.QLineEdit(self.groupBox_15)
        self.gp2_esq_prescrita.setGeometry(QtCore.QRect(80, 20, 41, 20))
        self.gp2_esq_prescrita.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gp2_esq_prescrita.setObjectName("gp2_esq_prescrita")
        self.gp2_esq_reflexiva = QtWidgets.QRadioButton(self.groupBox_15)
        self.gp2_esq_reflexiva.setGeometry(QtCore.QRect(30, 60, 91, 16))
        self.gp2_esq_reflexiva.setStyleSheet('font: 700 12pt "Calibri";')
        self.gp2_esq_reflexiva.setObjectName("gp2_esq_reflexiva")
        self.groupBox_16 = QtWidgets.QGroupBox(self.groupBox_14)
        self.groupBox_16.setGeometry(QtCore.QRect(150, 20, 131, 101))
        self.groupBox_16.setObjectName("groupBox_16")
        self.label_18 = QtWidgets.QLabel(self.groupBox_16)
        self.label_18.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_18.setStyleSheet('font: 700 12pt "Calibri";')
        self.label_18.setObjectName("label_18")
        self.gp2_dir_prescrita = QtWidgets.QLineEdit(self.groupBox_16)
        self.gp2_dir_prescrita.setGeometry(QtCore.QRect(80, 20, 41, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.gp2_dir_prescrita.setFont(font)
        self.gp2_dir_prescrita.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gp2_dir_prescrita.setObjectName("gp2_dir_prescrita")
        self.gp2_dir_reflexiva = QtWidgets.QRadioButton(self.groupBox_16)
        self.gp2_dir_reflexiva.setGeometry(QtCore.QRect(30, 60, 81, 16))
        self.gp2_dir_reflexiva.setStyleSheet('font: 700 12pt "Calibri";')
        self.gp2_dir_reflexiva.setObjectName("gp2_dir_reflexiva")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(890, 580, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(880, 610, 201, 31))
        self.lcdNumber.setStyleSheet(
            "color: rgb(0, 0, 0);\n" "background-color: rgb(255, 255, 255);\n" ""
        )
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(890, 490, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(882, 520, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1138, 21))
        self.menubar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.menubar.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(168, 168, 168, 255), stop:1 rgba(255, 255, 255, 255));\n"
            "color: rgb(0, 0, 0);\n"
            'font: 9pt "Arial";'
        )
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuCalcular = QtWidgets.QMenu(self.menubar)
        self.menuCalcular.setObjectName("menuCalcular")
        self.menuM_tdos_1_Grupo = QtWidgets.QMenu(self.menuCalcular)
        self.menuM_tdos_1_Grupo.setObjectName("menuM_tdos_1_Grupo")
        self.menuM_todo_SGF = QtWidgets.QMenu(self.menuM_tdos_1_Grupo)
        self.menuM_todo_SGF.setObjectName("menuM_todo_SGF")
        self.menuRelat_rios_da_simula_o = QtWidgets.QMenu(self.menubar)
        self.menuRelat_rios_da_simula_o.setObjectName("menuRelat_rios_da_simula_o")
        self.menuResultados = QtWidgets.QMenu(self.menubar)
        self.menuResultados.setObjectName("menuResultados")
        self.menuPropriedades = QtWidgets.QMenu(self.menubar)
        self.menuPropriedades.setObjectName("menuPropriedades")
        self.menuPot_ncia = QtWidgets.QMenu(self.menubar)
        self.menuPot_ncia.setObjectName("menuPot_ncia")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionM_todos_2_Grupo = QtWidgets.QAction(MainWindow)
        self.actionM_todos_2_Grupo.setObjectName("actionM_todos_2_Grupo")
        self.actionDiamond_Difference_DD = QtWidgets.QAction(MainWindow)
        self.actionDiamond_Difference_DD.setObjectName("actionDiamond_Difference_DD")
        self.actionDegrau_Caracter_stico = QtWidgets.QAction(MainWindow)
        self.actionDegrau_Caracter_stico.setObjectName("actionDegrau_Caracter_stico")
        self.actionSpectral_Green_s_Function = QtWidgets.QAction(MainWindow)
        self.actionSpectral_Green_s_Function.setObjectName(
            "actionSpectral_Green_s_Function"
        )
        self.actionReconstru_o = QtWidgets.QAction(MainWindow)
        self.actionReconstru_o.setObjectName("actionReconstru_o")
        self.actionNum_ricos_1G = QtWidgets.QAction(MainWindow)
        self.actionNum_ricos_1G.setObjectName("actionNum_ricos_1G")
        self.actionNum_ricos_2G = QtWidgets.QAction(MainWindow)
        self.actionNum_ricos_2G.setObjectName("actionNum_ricos_2G")
        self.actionF_sicos_Materiais_1G = QtWidgets.QAction(MainWindow)
        self.actionF_sicos_Materiais_1G.setObjectName("actionF_sicos_Materiais_1G")
        self.action_SICO_mATERIAIS_2g = QtWidgets.QAction(MainWindow)
        self.action_SICO_mATERIAIS_2g.setObjectName("action_SICO_mATERIAIS_2g")
        self.menuArquivo.addAction(self.actionSair)
        self.menuM_todo_SGF.addAction(self.actionSpectral_Green_s_Function)
        self.menuM_todo_SGF.addAction(self.actionReconstru_o)
        self.menuM_tdos_1_Grupo.addAction(self.menuM_todo_SGF.menuAction())
        self.menuM_tdos_1_Grupo.addAction(self.actionDiamond_Difference_DD)
        self.menuM_tdos_1_Grupo.addAction(self.actionDegrau_Caracter_stico)
        self.menuCalcular.addAction(self.menuM_tdos_1_Grupo.menuAction())
        self.menuCalcular.addAction(self.actionM_todos_2_Grupo)
        self.menuResultados.addAction(self.actionNum_ricos_1G)
        self.menuResultados.addAction(self.actionNum_ricos_2G)
        self.menuPropriedades.addAction(self.actionF_sicos_Materiais_1G)
        self.menuPropriedades.addAction(self.action_SICO_mATERIAIS_2g)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuCalcular.menuAction())
        self.menubar.addAction(self.menuRelat_rios_da_simula_o.menuAction())
        self.menubar.addAction(self.menuResultados.menuAction())
        self.menubar.addAction(self.menuPropriedades.menuAction())
        self.menubar.addAction(self.menuPot_ncia.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SIMULADOR"))
        self.groupBox.setTitle(_translate("MainWindow", "Problema"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Energia"))
        self.unigrupo.setText(_translate("MainWindow", "1 Grupo"))
        self.duogrupo.setText(_translate("MainWindow", "2 Grupos"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Possibilidade de fissão"))
        self.fonte_fixa.setText(_translate("MainWindow", "Não(Fonte Fixa)"))
        self.autovalor.setText(_translate("MainWindow", "Sim (Problema de Autovalor)"))
        self.label.setText(_translate("MainWindow", "Potência Gerada:"))
        self.label_2.setText(_translate("MainWindow", "MW"))
        self.ok_potencia.setText(_translate("MainWindow", "OK"))
        self.potencia_gerada.setToolTip(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center"><br/></p></body></html>',
            )
        )
        self.label_3.setText(_translate("MainWindow", "Condições de Contorno"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Grupo 1"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Esquerda"))
        self.label_6.setText(_translate("MainWindow", "Prescrita:"))
        self.radioButton_5.setText(_translate("MainWindow", "Reflexiva"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Direita"))
        self.label_16.setText(_translate("MainWindow", "Prescrita:"))
        self.radioButton_9.setText(_translate("MainWindow", "Reflexiva"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Grupo 1"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Esquerda"))
        self.label_8.setText(_translate("MainWindow", "Prescrita:"))
        self.gp1_esq_reflexiva.setText(_translate("MainWindow", "Reflexiva"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Direita"))
        self.label_17.setText(_translate("MainWindow", "Prescrita:"))
        self.gp1_dir_reflexiva.setText(_translate("MainWindow", "Reflexiva"))
        self.label_15.setText(
            _translate("MainWindow", "Fluxo escalar médio de nêutrons em um domínio")
        )
        self.label_20.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:10pt; font-weight:600;">Máximo</span></p></body></html>',
            )
        )
        self.label_21.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p><span style=" font-size:10pt; font-weight:600;">Mínimo</span></p></body></html>',
            )
        )
        self.groupBox_7.setTitle(
            _translate("MainWindow", "Domínio e Ordem de Quadratura")
        )
        self.label_4.setText(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                "</style></head><body style=\" font-family:'Calibri'; font-size:9pt; font-weight:700; font-style:normal;\">\n"
                '<p align="center" style=" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'Calibri\'; font-weight:700;">Número de </span></p>\n'
                '<p align="center" style=" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'Calibri\'; font-weight:700;">Regiões</span></p></body></html>',
            )
        )
        self.label_5.setText(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                "</style></head><body style=\" font-family:'Calibri'; font-size:9pt; font-weight:700; font-style:normal;\">\n"
                '<p align="center" style=" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'Calibri\'; font-weight:700;">Ordem da </span></p>\n'
                '<p align="center" style=" margin-top:2px; margin-bottom:2px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'Calibri\'; font-weight:700;">Quadratura</span></p></body></html>',
            )
        )
        self.ok_regioes.setText(_translate("MainWindow", "OK"))
        item = self.nodos_esp_zona.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nodos"))
        item = self.nodos_esp_zona.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Espessura(cm)"))
        item = self.nodos_esp_zona.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Zona"))
        item = self.nodos_esp_zona.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        self.label_22.setText(_translate("MainWindow", "(cm)"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Processo Iterativo"))
        self.label_11.setText(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                "</style></head><body style=\" font-family:'Calibri'; font-size:11pt; font-weight:700; font-style:normal;\">\n"
                '<p align="center" style=" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'Calibri\'; font-weight:700;">Iterações </span></p>\n'
                '<p align="center" style=" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'Calibri\'; font-weight:700;">Internas </span></p>\n'
                '<p align="center" style=" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'Calibri\'; font-weight:700;">(Total)</span></p></body></html>',
            )
        )
        self.label_12.setText(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><meta charset="utf-8" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "hr { height: 1px; border-width: 0; }\n"
                'li.unchecked::marker { content: "\\2610"; }\n'
                'li.checked::marker { content: "\\2612"; }\n'
                "</style></head><body style=\" font-family:'Calibri'; font-size:11pt; font-weight:700; font-style:normal;\">\n"
                '<p align="center" style=" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'Calibri\'; font-weight:700;">Iterações </span></p>\n'
                '<p align="center" style=" margin-top:1px; margin-bottom:1px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:\'Calibri\'; font-weight:700;">Externas </span></p>\n'
                "",
            )
        )
        self.label_13.setText(_translate("MainWindow", "Precisão"))
        self.label_14.setText(_translate("MainWindow", "Precisão"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Grupo 2"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Esquerda"))
        self.label_9.setText(_translate("MainWindow", "Prescrita:"))
        self.gp2_esq_reflexiva.setText(_translate("MainWindow", "Reflexiva"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Direita"))
        self.label_18.setText(_translate("MainWindow", "Prescrita:"))
        self.gp2_dir_reflexiva.setText(_translate("MainWindow", "Reflexiva"))
        self.label_7.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Duração do cálculo (s):</p></body></html>',
            )
        )
        self.label_19.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Etapa:</p></body></html>',
            )
        )
        self.lineEdit.setText(_translate("MainWindow", "NÃO INICIADO"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuCalcular.setTitle(_translate("MainWindow", "Calcular"))
        self.menuM_tdos_1_Grupo.setTitle(_translate("MainWindow", "Métdos 1 Grupo"))
        self.menuM_todo_SGF.setTitle(_translate("MainWindow", "Método SGF"))
        self.menuRelat_rios_da_simula_o.setTitle(
            _translate("MainWindow", "Relatórios da simulação")
        )
        self.menuResultados.setTitle(_translate("MainWindow", "Resultados"))
        self.menuPropriedades.setTitle(_translate("MainWindow", "Propriedades"))
        self.menuPot_ncia.setTitle(_translate("MainWindow", "Potência"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
        self.actionM_todos_2_Grupo.setText(_translate("MainWindow", "Métodos 2 Grupo"))
        self.actionDiamond_Difference_DD.setText(
            _translate("MainWindow", "Diamond Difference (DD)")
        )
        self.actionDegrau_Caracter_stico.setText(
            _translate("MainWindow", "Degrau Característico")
        )
        self.actionSpectral_Green_s_Function.setText(
            _translate("MainWindow", "Spectral Green´s Function")
        )
        self.actionReconstru_o.setText(_translate("MainWindow", "Reconstrução"))
        self.actionNum_ricos_1G.setText(_translate("MainWindow", "Numéricos - 1G"))
        self.actionNum_ricos_2G.setText(_translate("MainWindow", "Numéricos - 2G"))
        self.actionF_sicos_Materiais_1G.setText(
            _translate("MainWindow", "Físico Materiais - 1G")
        )
        self.action_SICO_mATERIAIS_2g.setText(
            _translate("MainWindow", "Físico Materiais - 2G")
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
