# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resultados_Numericos_1G.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(911, 480)
        self.fundo = QtWidgets.QLabel(Dialog)
        self.fundo.setGeometry(QtCore.QRect(-110, -120, 1051, 721))
        self.fundo.setStyleSheet("background-color: rgb(205, 232, 210);")
        self.fundo.setText("")
        self.fundo.setObjectName("fundo")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 451, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(62)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet(
            "QGroupBox {\n"
            '    font: 500 10pt "Segoe UI";\n'
            "    border: 1px solid black;  /* Cor da borda preta */\n"
            "}\n"
            ":title {\n"
            "    subcontrol-origin: margin;\n"
            "    subcontrol-position: top left; /* Posição no canto superior esquerdo */\n"
            "    left: 5px; /* Ajuste horizontal */\n"
            "    top: -5px; /* Ajuste vertical */\n"
            "}"
        )
        self.groupBox.setObjectName("groupBox")
        self.fluxos_escalares = QtWidgets.QTableWidget(self.groupBox)
        self.fluxos_escalares.setGeometry(QtCore.QRect(5, 20, 441, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fluxos_escalares.setFont(font)
        self.fluxos_escalares.setObjectName("fluxos_escalares")
        self.fluxos_escalares.setColumnCount(0)
        self.fluxos_escalares.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.fluxos_escalares.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.fluxos_escalares.setVerticalHeaderItem(1, item)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 190, 451, 111))
        self.groupBox_2.setStyleSheet(
            "QGroupBox {\n"
            '    font: 500 10pt "Segoe UI";\n'
            "    border: 1px solid black;  /* Cor da borda preta */\n"
            "}\n"
            ":title {\n"
            "    subcontrol-origin: margin;\n"
            "    subcontrol-position: top left; /* Posição no canto superior esquerdo */\n"
            "    left: 5px; /* Ajuste horizontal */\n"
            "    top: -4px; /* Ajuste vertical */\n"
            "}\n"
            ""
        )
        self.groupBox_2.setObjectName("groupBox_2")
        self.absorcao = QtWidgets.QTableWidget(self.groupBox_2)
        self.absorcao.setGeometry(QtCore.QRect(10, 20, 431, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.absorcao.setFont(font)
        self.absorcao.setObjectName("absorcao")
        self.absorcao.setColumnCount(1)
        self.absorcao.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.absorcao.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.absorcao.setHorizontalHeaderItem(0, item)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(470, 50, 431, 381))
        self.groupBox_3.setStyleSheet(
            "QGroupBox {\n"
            '    font: 500 10pt "Segoe UI";\n'
            "    border: 1px solid black;  /* Cor da borda preta */\n"
            "}\n"
            ":title {\n"
            "    subcontrol-origin: margin;\n"
            "    subcontrol-position: top left; /* Posição no canto superior esquerdo */\n"
            "    left: 5px; /* Ajuste horizontal */\n"
            "    top: -5px; /* Ajuste vertical */\n"
            "}\n"
            ""
        )
        self.groupBox_3.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop
        )
        self.groupBox_3.setObjectName("groupBox_3")
        self.fluxos_angulares = QtWidgets.QTableWidget(self.groupBox_3)
        self.fluxos_angulares.setGeometry(QtCore.QRect(10, 20, 411, 351))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fluxos_angulares.setFont(font)
        self.fluxos_angulares.setObjectName("fluxos_angulares")
        self.fluxos_angulares.setColumnCount(0)
        self.fluxos_angulares.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.fluxos_angulares.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.fluxos_angulares.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.fluxos_angulares.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.fluxos_angulares.setVerticalHeaderItem(3, item)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 310, 451, 121))
        self.groupBox_4.setStyleSheet(
            "QGroupBox {\n"
            '    font: 500 10pt "Segoe UI";\n'
            "    border: 1px solid black;  /* Cor da borda preta */\n"
            "}\n"
            ":title {\n"
            "    subcontrol-origin: margin;\n"
            "    subcontrol-position: top left; /* Posição no canto superior esquerdo */\n"
            "    left: 5px; /* Ajuste horizontal */\n"
            "    top: -5px; /* Ajuste vertical */\n"
            "}\n"
            ""
        )
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.ponto_0_fuga = QtWidgets.QLineEdit(self.groupBox_4)
        self.ponto_0_fuga.setGeometry(QtCore.QRect(120, 20, 121, 31))
        self.ponto_0_fuga.setObjectName("ponto_0_fuga")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.ponto_x = QtWidgets.QLineEdit(self.groupBox_4)
        self.ponto_x.setGeometry(QtCore.QRect(80, 70, 41, 31))
        self.ponto_x.setObjectName("ponto_x")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(130, 70, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.ponto_x_fuga = QtWidgets.QLineEdit(self.groupBox_4)
        self.ponto_x_fuga.setGeometry(QtCore.QRect(170, 70, 121, 31))
        self.ponto_x_fuga.setObjectName("ponto_x_fuga")
        self.mostrar_valores = QtWidgets.QPushButton(Dialog)
        self.mostrar_valores.setGeometry(QtCore.QRect(10, 440, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.mostrar_valores.setFont(font)
        self.mostrar_valores.setObjectName("mostrar_valores")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Resultados Numéricos 1 Grupo"))
        self.groupBox.setTitle(_translate("Dialog", "Fluxos Escalares"))
        item = self.fluxos_escalares.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "Fluxos"))
        item = self.fluxos_escalares.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "X (cm)"))
        self.label.setText(_translate("Dialog", "Análise Espectral"))
        self.groupBox_2.setTitle(_translate("Dialog", "Taxa de Absorção por Região"))
        item = self.absorcao.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "Taxas"))
        item = self.absorcao.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        self.groupBox_3.setTitle(_translate("Dialog", "Fluxos Angulares"))
        item = self.fluxos_angulares.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.fluxos_angulares.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "2"))
        item = self.fluxos_angulares.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "3"))
        item = self.fluxos_angulares.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "4"))
        self.groupBox_4.setTitle(_translate("Dialog", "Taxa de Fuga"))
        self.label_2.setText(
            _translate(
                "Dialog",
                '<html><head/><body><p><span style=" font-size:10pt;">No ponto 0 cm = </span></p></body></html>',
            )
        )
        self.label_3.setText(
            _translate(
                "Dialog",
                '<html><head/><body><p><span style=" font-size:10pt;">No ponto</span></p></body></html>',
            )
        )
        self.label_4.setText(
            _translate(
                "Dialog",
                '<html><head/><body><p><span style=" font-size:10pt;">cm =</span></p></body></html>',
            )
        )
        self.mostrar_valores.setText(_translate("Dialog", "Mostrar Valores"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
